version: '3'

services:

  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    environment:
      - AXONSERVER_HOSTNAME=axonserver
    ports:
      - 8024:8024

  command-service:
    build:
      context: .
      dockerfile: ./command-service/Dockerfile
    environment:
      - AXONSERVER_HOST=axonserver
    ports:
      - 8081:8080

  query-service:
    build:
      context: .
      dockerfile: ./query-service/Dockerfile
    environment:
      - AXONSERVER_HOST=axonserver
    ports:
      - 8082:8080
